version: '3.8'

services:
    mongo:
        container_name: db
        image: mongo:6-jammy
        restart: always
        ports:
            - '27017:27017'
        networks:
            - shared-network
        volumes:
            - ./mongo-db:/var/lib/mongodb/data
    api:
        container_name: backend
        restart: unless-stopped
        image: todo-api-prod:1.0.0
        build:
            context: api
            target: production
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - DB_URI=mongodb://mongo:27017/todo
            - PORT=5000
        networks:
            - shared-network
        depends_on:
            - mongo

networks:
    shared-network:
